### PR TITLE
Bump to support rails 5.0.0

### PR DESCRIPTION
**Pull request by acoravos**
Update to `activesupport` for Rails 5.0.0.

### CODE REVIEW

**Comment by pda** [comment]
Thanks 👍

**Comment by kwent** [comment]
Hi @pda 

Could you also publish `1.0.2` and `1.0.3` on https://rubygems.org ?

Thanks for your hard work !

**Comment by pda** [comment]
Thanks @kwent and @stevepaulo for the reminder. Will try to tag and publish some versions later today.

**Comment by pda** [comment]
Tagged as v1.1.0 and pushed: https://rubygems.org/gems/flip/versions/1.1.0

**Pull request merged**
